### ISSUE TITLE
Update package metadata on PyPI?

### ISSUE THREAD

**Issue by levitsky** [mobiusklein/psims#15]
Right now `proforma` tests in Pyteomics are failing on Python 2.7, 3.6 and 3.7. Apparently the latest `psims` doesn't work on these versions, but it is still installed on those when running `pip install psims`.

Would this be fixed by updating the PyPI entry?

Edit: on second thought, the current latest release would probably have to be removed completely, or `pip-3.7` and the others will choose it over the whatever newer version is uploaded.

**Comment by mobiusklein** [comment]
I've initiated the release workflow. If I understand the way Python versions are permitted, I have Trove classifiers for just Py3.8+ in `setup.py` now, so that should fix the first problem. I'll go yank the previous release.

**Comment by mobiusklein** [comment]
All releases not testing on Py27 prior to the 0.1.48 have been yanked. That _should_ do it.

**Comment by levitsky** [comment]
Unfortunately 0.1.48 still gets installed on all versions. Could it be because of the universal `py2.py3` wheel?

**Comment by mobiusklein** [comment]
I've removed the universal wheel and uploaded a non-universal one built on Py3

**Comment by levitsky** [comment]
I'm not sure how, but 0.1.48 is still the one installed across all versions. On Py2 it's installed from source tarball, on 3.6 and 3.7 it's from the `py3` wheel.

**Comment by mobiusklein** [comment]
It looks like Trove classifiers don't do anything, but passing `python_requires` to `setuptools.setup` does. I've uploaded another release 0.1.49 with that set to only accept Python versions > 3.7.

**Comment by levitsky** [comment]
Now 0.1.45 is installed on 2.7 and 3.6, which is good, but 0.1.49 is still installed on Python 3.7.

**Comment by mobiusklein** [comment]
Yanked 0.1.49, added 0.1.50 with >3.8 specified instead of >3.7. >3.7 must mean >3.7.0.

**Comment by levitsky** [comment]
That seems to have solved it. Thank you!
